// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeBK3SDhuevhZIqJg6BPDU1Tmd9HXRgxU',
    appId: '1:664835202666:web:28e0827dff8136c0c1b413',
    messagingSenderId: '664835202666',
    projectId: 'siwarga',
    authDomain: 'siwarga.firebaseapp.com',
    storageBucket: 'siwarga.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSEuG8DeOwyiQGtmvk9ropHF-UqvJcdec',
    appId: '1:664835202666:android:b5483b64e14936e7c1b413',
    messagingSenderId: '664835202666',
    projectId: 'siwarga',
    storageBucket: 'siwarga.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoOSYwuIru0A2FW9bXcKuwLQquEIaauAM',
    appId: '1:664835202666:ios:8d08cd3af13a985cc1b413',
    messagingSenderId: '664835202666',
    projectId: 'siwarga',
    storageBucket: 'siwarga.firebasestorage.app',
    iosBundleId: 'com.example.siWarga',
  );
}
